### ISSUE TITLE
FFMpegWriter input and output dict format

### ISSUE THREAD

**Issue by kr-hansen** [scikit-video/scikit-video#11]
I installed the most recent version of scikit-video, and I was wondering if there is an example format for the inputdict or outputdict formats or keys.  Going through the tutorial at (http://www.scikit-video.org/stable/io.html) the given example of this code doesn't work as written with the current version of scikit-video:

`writer = skvideo.io.FFmpegWriter("outputvideo.mp4", (5, 480, 640, 3))`

Is there a way an example could be provided of what the inputdict and outputdict values would be to alter the parameters of FFmpegWriter?

**Comment by beyondmetis** [comment]
Ah good catch. I will have to update the documentation about FFmpegWriter. I'm in the process of writing more example-based documentation. You can see the current progress (with dict examples for I/O) here:

http://www.scikit-video.org/dev/examples.html

**Comment by PetreanuAndi** [comment]
Hey guys. Check this code : 
----------------------------------------
from skvideo.io import VideoWriter
import numpy
writer = VideoWriter(filename, frameSize=(w, h))
writer.open()
writer.write("some random video frame")
-------------------------------------------
It does output a video file, however the quality of it is very poor beyond the first keyframe. Your skvideo documentation states that FFmpegWriter should be used for more customisation of parameters, however that does not exist.

http://www.scikit-video.org/dev/examples.html this link does not provide an example of video file written to disk frame by frame.

What's wrong with this thread? Why is there such bad quality of output? Why is there such bad quality of documentation? 

Why is there no proper way to write video in Python, in 2016? :)

**Comment by beyondmetis** [comment]
Ah! I did forget to add an example on the webpage regarding high-quality h264 encodes.

If you want to output a good quality video (frame by frame), you can start from the below example which uses the libx264 codec with bitrate set to 30MBps which encodes random noise:

    import skvideo.io
    import skvideo.measure
    outputfile = sys._getframe().f_code.co_name + ".mp4"
    outputdata = np.random.random(size=(30, 480, 640, 3)) * 255
    outputdata = outputdata.astype(np.uint8)

    # start the FFmpeg writing subprocess with following parameters
    writer = skvideo.io.FFmpegWriter(outputfile, outputdict={
        '-vcodec': 'libx264', '-b': '30000000'
    })

    for i in range(30):
        writer.writeFrame(outputdata[i])
    writer.close()

    inputdata = skvideo.io.vread(outputfile)

    # test each frame's SSIM score
    mSSIM = 0
    for i in range(30):
        mSSIM += skvideo.measure.ssim(np.mean(inputdata[i], axis=2), np.mean(outputdata[i], axis=2))
    mSSIM /= 30.0

    print mSSIM

You can play with the coding parameters and see how it is reflected in the measured mean SSIM value. BTW, the flags in the outputdict are passed directly to FFmpeg through the CLI.

Perhaps there is a better, more generic way to write high quality video as h264, rather than explicitly using a dictionary of parameters. I think the current approach is flexible although currently poorly documented.

**Comment by beyondmetis** [comment]
I have now added this to the dev branch of the website

**Comment by TobiasWeis** [comment]
It would be awesome if you could state somewhere whether it's possible to grab frames from a webcam? Have not been able to find any documentation on that in the latest release, and had no luck with ffmpegreader so far..

**Comment by beyondmetis** [comment]
What have you tried, and what platform are you using? If on Linux, I think
it could work if you point the input file to /dev/video0, but I haven't
tried that.

On Nov 22, 2017 8:23 PM, "Tobi" <notifications@github.com> wrote:

It would be awesome if you could state somewhere whether it's possible to
grab frames from a webcam? Have not been able to find any documentation on
that in the latest release, and had no luck with ffmpegreader so far..

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/scikit-video/scikit-video/issues/11#issuecomment-346519467>,
or mute the thread

**Comment by dukleryoi** [comment]
Hi,
Thanks for the ice package!
I am working with skvideo and trying to output a video but while the code above (high quality video) runs and produces a video file, the created video is not being able to be read by Window media player/ does not have any frames. Do you know what is causing the problem and how could I fix this?

**Comment by beyondmetis** [comment]
Is the file size larger than 0? You can try playing it with VLC

**Comment by dukleryoi** [comment]
Hi, I downloaded VLC and it works perfectly! Thank you.

**Comment by oxydron** [comment]
Until today we don't have a simple documentation for outputdict from FFmpegWriter. Is one of the most important things on this lib. How can I define how to write an video? Nowhere with explanations? A single example?
