### ISSUE TITLE
Is there any way to read the alpha channel from a video different pixel format such as yuva444p10le?

### ISSUE THREAD

**Issue by jvmassaro** [scikit-video/scikit-video#114]
I'm trying to read in prores compressed video and write it back out without loss of data, but I'm losing data somewhere. I think the loss of data is coming from the lack of an alpha channel being read in. The pixel format I'm trying to read is yuva444p10le, but I have to read in as rgb48le. I can still write out yuva444p10le, but there are now compression artifacts and I believe this is coming from having to read in the data as rgb instead of rgba or yuva. Any ideas?

**Comment by jvmassaro** [comment]
When I try using outputdict={"-pix_fmt": "yuva444p10le"} I get: 
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\skvideo\io\abstract.py", line 200, in __init__
    raise ValueError(outputdict['-pix_fmt'] + 'is not a valid pix_fmt for numpy conversion')
ValueError: yuva444p10le is not a valid pix_fmt for numpy conversion
So I digged through abstract.py and it only looks like rbg48le is the only pixel format supported.

**Comment by beyondmetis** [comment]
Ah, this format doesn't appear to be supported. To support it requires a 10 bit datatype. However, I think your problem can easily be solved by loading the video in as pix_fmt yuva444p16le, which I believe is supported. The end result will be that you need an extra 6 bits per channel when loading the video into the numpy array. You should not lose any quality.

**Comment by jvmassaro** [comment]
Ok, that helped, I can now read in yuva444p16le, but it seems the data is read in a rgba64 and I need to convert back to rgba in order for the colors to be correct. If I don't do the conversion I'm writing rgba to yuva. There's also a color shift, that I think could be the result of the conversion to 16-bit from 10-bit and then the color conversion yuva to rgba. Do you think this is the issue or could it be something else I'm missing. I tried dividing by 64 to convert to 10 bits before writing out the video file but this results in either a black in or a green image depending on when I do the color conversion. Any ideas? Thanks again.

**Comment by beyondmetis** [comment]
Can you post the few lines of code that you are using to read that data in and write it out again?

The video writer will need to know that you are providing it a yuva444p16le pix_fmt input and writing a yuva444p10le pix_fmt output. By default, it assumes rgb24 input, since that's usually what folks use when creating video frames.

**Comment by beyondmetis** [comment]
Ah, I believe I see what's wrong. You need to specify in the inputparms dictionary that your pixel format is yuva444p16le. Basically, this:
`
inputparms = {"-pix_fmt": "yuva444p16le"}
outputparms = {"-vcodec": "prores", "-pix_fmt": "yuva444p10le", "-bits_per_raw_sample": "10", "-s": "2500x1100"}
writer = skvideo.io.FFmpegWriter(outfile, inputdict = inputparms, outputdict=outputparms)
`
You can then remove the opencv conversion. Your colors might appear incorrect because there is a different interpretation of YUV amongst different tools. Could also be color conversion artifacts since we have yuv->rgb->yuv.

**Comment by jvmassaro** [comment]
Ok this worked! Thank you! I just wonder why the video went from 100 MB to 67MB? The audio was stripped, but it's only a one second clip so probably not a significant reduction.

**Comment by beyondmetis** [comment]
Not sure. Could there be any type of compression happening in the prores container?
