### ISSUE TITLE
'scipy.misc' has no attribute 'imresize'

### ISSUE THREAD

**Issue by PulkitMishra** [scikit-video/scikit-video#122]
skvideo.measure.niqe fails with the above error

**Comment by stg7** [comment]
I have the same issue with brisque.py

(mentioned in scipy: "imresize is deprecated! imresize is deprecated in SciPy 1.0.0, and will be removed in 1.3.0. Use Pillow instead: numpy.array(Image.fromarray(arr).resize())." https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imresize.html)

i changed it in brisque.py

```
import PIL
from PIL import Image
....

half_scale = scipy.misc.imresize(full_scale, 0.5, interp='bicubic', mode='F')
-to->
half_scale = np.array(Image.fromarray(full_scale).resize(
(int(0.5 * full_scale.shape[0]), int(full_scale.shape[1] * 0.5)),
resample=PIL.Image.BICUBIC)
)
...
```

however i'm not sure what mode="F" means, and if the values are somehow different, due to 
the width and height estimation. a validation should be performed.

i did the same changes for niqe.py.
```
import PIL
from PIL import Image
...

img2 = scipy.misc.imresize(img, 0.5, interp='bicubic', mode='F')
-to->
img2 = np.array(Image.fromarray(img).resize(
    (int(0.5 * img.shape[0]), int(img.shape[1] * 0.5)),
    resample=PIL.Image.BICUBIC)
)

```

best
Steve

**Comment by stg7** [comment]
full diff here: https://github.com/stg7/scikit-video/commit/87f878b96bf00cb19d850992f01d9370b57b8345

i already created a fork and a pull request for this issue

**Comment by stg7** [comment]
I observed a problem with the unit tests, so i tried to include the "mode="F"" parameter and lets see how it will work (ceba4a7773adc97cab502bc10fd9a53535984622)

**Comment by PulkitMishra** [comment]
#123 closes this
