### ISSUE TITLE
Get frame timestamp

### ISSUE THREAD

**Issue by zacharynevin** [scikit-video/scikit-video#29]
Hello,

I am using `skvideo.io.vreader` to read a file as a stream:
```
videogen = skvideo.io.vreader(video_url) # s3 path to the video
for frame in videogen:
        # do stuff
        # get timestamp of frame
```
I want to get the timestamp of the frame relative to the start of the video. I couldn't find anything in the API docs related to this. Is it possible?

**Comment by beyondmetis** [comment]
I actually never tested loading URL paths. Does that part work?

If you multiply the frame number by the frame rate, you can get the number of seconds that elapsed since the beginning of the video. You could then convert the seconds to a timestamp. The frame rate (if it exists in the video metadata) can be read using the skvideo.io.ffprobe function.

**Comment by zacharynevin** [comment]
That was my bad - I assumed that you could use URL paths. You can't, so I just download the file first and then load it in.

I will try this. Thanks!

**Comment by zacharynevin** [comment]
It works, thanks!
