### ISSUE TITLE
About Detecting scene boundaries

### ISSUE THREAD

**Issue by xiamenwcy** [scikit-video/scikit-video#31]
Hi,thank you for this beautiful work! It's very useful for me! But I found a issue that when I run the example:[Detecting scene boundaries Demo](http://www.scikit-video.org/stable/examples/scene.html#sceneexample ) ,the result I got differs from yours. 
Here is my result. [click it](https://goo.gl/photos/qEf9c5gRDzkjcN1V6) .I guess in the code that
``scene_lum_idx = skvideo.measure.scenedet(videodata, method='intensity', parameter1=1.0)``  ,parameter1
is uncorrected! Can you help me?

**Comment by beyondmetis** [comment]
I think the latest website documentation is slightly out of date. I changed "intensity" to "histogram" at some point, since that was more accurate. Then I placed a different algorithm under "intensity".

Feel free to try histogram, and please let me know if that works. Up-to-date documentation is here:
http://www.scikit-video.org/dev/modules/generated/skvideo.measure.scenedet.html#skvideo.measure.scenedet
