### ISSUE TITLE
Live camera feed

### ISSUE THREAD

**Issue by AndersonReyes** [scikit-video/scikit-video#37]
having camera capture feed would be cool

**Comment by beyondmetis** [comment]
Do you mean from a webcam, over a network, or both?

**Comment by AndersonReyes** [comment]
Webcam. I haven't looked up how to implement it myself but I can give it a try. Right now we have to use opecv on top of scikit video just for live webcam feed.

**Comment by beyondmetis** [comment]
This is interesting. There's nothing stopping us from implementing this, since the ffmpeg backend can support this by itself. It's just a matter of wrapping a function around ffmpeg/libav. 

According to https://trac.ffmpeg.org/wiki/Capture/Webcam, the live feed can be dumped using:
ffmpeg -i /dev/video0 output.mp4

On windows:
ffmpeg -y -f vfwcap -i 0 output.mp4

**Comment by AndersonReyes** [comment]
word I'll start there

**Comment by AndersonReyes** [comment]
Hmmm from what I see the feed is always dumped to output file so then we'd be dumping and reading concurrently and using a generator to get the frame

**Comment by beyondmetis** [comment]
Have you considered pipes? That's what scikit-video currently uses. FFmpeg actually gets called like:

ffmpeg -i inputfile.mp4 -

The '-' means pipe to stdout. I'm not sure how this will be handled internally when providing a webcam as input. It might just work :)

**Comment by AndersonReyes** [comment]
That or should be able to read the raw video data coming in anf convert it to numpy arrays. Hmm I think I got a solution give me a few weeks (it's finals for me lol..undergrad problems lol) I'll hack at it.

**Comment by beyondmetis** [comment]
Actually, you can pipe std out right into numpy arrays. This is exactly what scikit-video does under the hood :)
