### ISSUE TITLE
frame rate of the last frame in the video

### ISSUE THREAD

**Issue by s885219s** [scikit-video/scikit-video#42]
Hello,

I am trying to make videos with images,

so I use `skvideo.io.FFmpegWriter` and `writeFrame` to write them frame by frame.

```
writer = skvideo.io.FFmpegWriter(outputMp4,
                                 inputdict={
                                     '-r':'1'
                                 },
                                 outputdict={
                                     '-vcodec':'libx264',
                                     '-b': '30000000'
                                 })  
for i in resizeImagesMp4:
    writer.writeFrame(i)
writer.close()

```

However, when I set up a new frame rate, it do not work on the last image.

In other words, all the images in the video will delay for a second except for the last one.

How can I fix it?

Thanks a lot.

**Comment by beyondmetis** [comment]
I verified your problem, but I'm not sure it's wrong behavior. The frame rate controls the time it takes until the next frame is presented. Video players will arrive at the last frame, then since no other frames are left to present, the video playback is finished. If you set the video player to not close after finishing, this is a non-issue.

If you don't mind having an extra frame in your output video, you can always add the last frame twice. Lastly, there might be some video metadata that tells the video player to wait after all frames are completely rendered, but I've never seen it.

**Comment by s885219s** [comment]
Oh, I see!

Sorry, I forgot to tell you that I want to loop my video at the very beginning.

So, the frame delay of the last frame is very important to me.

Now I know how the rate controls work, as you said, I think I can solve this problem by adding the last frame twice or add the first frame in the end.

Thanks, it helps me a lot.

**Comment by beyondmetis** [comment]
Great!
