### ISSUE TITLE
 if tags['@key'] == 'rotate':      TypeError: string indices must be integers

### ISSUE THREAD

**Issue by identidata** [scikit-video/scikit-video#43]
Hi,

I reported a bug a couple of days ago and one of you was very nice to fix it asap. The problem was reading files created on mobiles.

However, after the fix, we are having problems reading files created on web (webm files). Before the fix, this used to work.

Last time I sent the video, please ping me if you would like me to send one again (alejandro@identidata.io)

    Traceback (most recent call last):
      File "test_video.py", line 13, in <module>
        videogen = skvideo.io.vread(video)
       File "/home/ubuntu/data_2/scikit-video/skvideo/io/io.py", line 144, in vread
        reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
      File "/home/ubuntu/data_2/scikit-video/skvideo/io/ffmpeg.py", line 115, in 
    __init_
   
       if tags['@key'] == 'rotate':
      TypeError: string indices must be integers

**Comment by beyondmetis** [comment]
Just sent you an email request for data :)

**Comment by identidata** [comment]
thanks so much again!

Alejandro Simkievich
CEO | *identidata.io <http://identidata.io>*
M: +55 (11) 99634-6673
skype: asimkievich

**Comment by beyondmetis** [comment]
Please pull and try again. I expect that it should work with all videos

**Comment by identidata** [comment]
yes it does sir, thanks so much again. Issue can be closed.

Question, maybe off topic if you do not mind,. I noticed that all color
videos (ios, android, web) are coming in RGB (as opposed to BRG) in our
case. As a default, do most videos use to come in RBG or that is an
assumption you cannot make?

Thanks so much again for everything.

Alejandro Simkievich
CEO | *identidata.io <http://identidata.io>*
M: +55 (11) 99634-6673
skype: asimkievich

**Comment by beyondmetis** [comment]
All image and video processing that I have seen (outside of OpenCV) use RGB storage formats instead of BGR. I tried to find a reason for using BGR, but I couldn't find a good one outside of "legacy" reasons. Anytime OpenCV is used, you must always remember to flip the channels, which is unfortunate. If scikit-video were to load videos into BGR by default instead, we would not be able to use matplotlib or scikit-image without swizzling the bytes.

That being said, you CAN actually use BGR by using the correct setting. Try this:

`reader = skvideo.io.FFmpegReader(video, outputdict={
  '-pix_fmt' : 'bgr24'
}
)`
