### ISSUE TITLE
Videos made with skvideo.io.vwrite can't be opened with QuickTime player

### ISSUE THREAD

**Issue by adamcasson** [scikit-video/scikit-video#74]
Wondering if anyone has had this issue as well. I write an mp4 file with skvideo.io.vwrite and when I try to view it with QuickTime player on Mac I get an error

`The file isn’t compatible with QuickTime Player.`

I can view it fine with VLC player however.

**Comment by beyondmetis** [comment]
You can try changing the output codec in vwrite to use libx264 or mpeg2video to see if that helps.

**Comment by adamcasson** [comment]
I tried
`skvideo.io.vwrite('video.mp4', frames, outputdict={"-vcodec":"libx264"})`
and got the same error when opening the video file with QuickTime

and
`skvideo.io.vwrite('video.mp4', frames, outputdict={"-vcodec":"mpeg2video"})`
QuickTime behaves differently with this but still can't open it and says "The operation could not be completed"

**Comment by beyondmetis** [comment]
According to:

https://stackoverflow.com/questions/14430593/encoding-a-readable-movie-by-quicktime-using-ffmpeg

You can try setting output pix_fmt to yuv420p in vwrite.

On Mar 16, 2018 12:51 PM, "Adam Casson" <notifications@github.com> wrote:

I tried
skvideo.io.vwrite('video.mp4', frames, outputdict={"-vcodec":"libx264"})
and got the same error when opening the video file with QuickTime

and
skvideo.io.vwrite('video.mp4', frames, outputdict={"-vcodec":"mpeg2video"})
QuickTime behaves differently with this but still can't open it and says
"The operation could not be completed"

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/scikit-video/scikit-video/issues/74#issuecomment-373793713>,
or mute the thread
